import { createWorldRecipe } from "./worldRecipe";

export const spaceRecipe = createWorldRecipe({
  id: "spacelab-solar-system-v1",
  name: "Copernix Space Lab: Solar System",
  type: "space",
  seed: "copernix-space-solar-001",
  location: {
    planet: "Solar System",
    country: "",
    region: "",
    city: "",
    place: "Heliocentric training scene",
  },
  layers: [
    { id: "starfield", name: "Stars", type: "background" },
    { id: "solar-system", name: "Solar System", type: "orbits" },
    { id: "asteroids", name: "Asteroids", type: "near-earth-objects" },
    { id: "comets", name: "Comets", type: "flyby-effects" },
    { id: "missions", name: "Missions", type: "education" },
  ],
  pointsOfInterest: [
    {
      id: "sun",
      name: "Sun",
      localName: "Słońce",
      type: "star",
      orbit: 0,
      radius: 2.4,
      narration: "Słońce jest gwiazdą w centrum naszego Układu Słonecznego.",
    },
    {
      id: "mercury",
      name: "Mercury",
      localName: "Merkury",
      type: "rocky-planet",
      orbit: 4.2,
      radius: 0.28,
      narration: "Merkury okrąża Słońce w 88 dni.",
    },
    {
      id: "venus",
      name: "Venus",
      localName: "Wenus",
      type: "rocky-planet",
      orbit: 7.1,
      radius: 0.58,
      narration: "Wenus jest bardzo gorącą planetą z gęstą atmosferą.",
    },
    {
      id: "earth",
      name: "Earth",
      localName: "Ziemia",
      type: "rocky-planet",
      orbit: 12,
      radius: 0.95,
      narration: "Ziemia ma oceany, chmury i prowadzi do Terra Mode.",
    },
    {
      id: "mars",
      name: "Mars",
      localName: "Mars",
      type: "rocky-planet",
      orbit: 15.4,
      radius: 0.46,
      narration: "Mars ma czerwony pył i wysokie kosmiczne góry.",
    },
    {
      id: "jupiter",
      name: "Jupiter",
      localName: "Jowisz",
      type: "gas-giant",
      orbit: 22.5,
      radius: 1.35,
      narration: "Jowisz jest największą planetą Układu Słonecznego.",
    },
    {
      id: "saturn",
      name: "Saturn",
      localName: "Saturn",
      type: "gas-giant",
      orbit: 30,
      radius: 1.08,
      rings: true,
      narration: "Saturn ma wielkie pierścienie z lodu i skał.",
    },
    {
      id: "uranus",
      name: "Uranus",
      localName: "Uran",
      type: "ice-giant",
      orbit: 38,
      radius: 0.78,
      narration: "Uran obraca się prawie na boku.",
    },
    {
      id: "neptune",
      name: "Neptune",
      localName: "Neptun",
      type: "ice-giant",
      orbit: 46,
      radius: 0.76,
      narration: "Neptun ma jedne z najszybszych wiatrów w Układzie Słonecznym.",
    },
  ],
  narration: {
    guide: "Luna",
    intro: "Kliknij planetę, żeby usłyszeć krótką ciekawostkę.",
    entries: ["Sun", "Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"],
  },
  weather: {
    provider: "none",
    fallback: "",
  },
  assets: {
    basePath: "",
    images: {},
  },
});
